### ISSUE TITLE
Only pulls from MyQ Hub and not Assurelink Hub

### ISSUE THREAD

**Issue by michaelmac8** [kennethklee/webthings-myq-adapter#3]
I have a Craftsman Assurelink hub that is connected to my MyQ account, however the addon does not show my Assurelink connected opener.

**Comment by kennethklee** [comment]
unfortunately i don't own any assurelink products and wouldn't be able to test.

this project wraps the `myq-api` library with an webthings adapter. perhaps this issue might interest them.
